"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:57:37.849677+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from datetime import timezone
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, lit, broadcast, when
from pyspark.sql.types import StructType, StructField, StringType, DecimalType, TimestampType
import os
from dotenv import load_dotenv
load_dotenv()

import warnings
warnings.filterwarnings("ignore")
from datetime import datetime, timezone


def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read transactions and promotions data
    transactions_df = (spark.read.format("parquet")
                      .option("header", "true")
                       .load(f"{input_path}/transactions")
                       .withColumn("ingestion_timestamp", current_timestamp())
                       .withColumn("source_file_name", lit("transactions.parquet"))
                       .withColumn("batch_id", lit(run_id)))

    promotions_df = (spark.read.format("csv")
                    .option("header", "true")
                    .load(f"{input_path}/promotions")
                    .withColumn("ingestion_timestamp", current_timestamp())
                    .withColumn("source_file_name", lit("promotions.csv"))
                    .withColumn("batch_id", lit(run_id)))

    # Write data to Bronze layer
    transactions_df.write.partitionBy("transaction_date").parquet(f"{output_path}/transactions")
    promotions_df.write.partitionBy("promo_id").parquet(f"{output_path}/promotions")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze layer data
    transactions_bronze_df = (spark.read.format("parquet")
                              .load(f"{bronze_path}/transactions")
                              .where(col("transaction_date") == run_date))

    promotions_bronze_df = (spark.read.format("parquet")
                            .load(f"{bronze_path}/promotions"))

    # Cast columns and apply filters
    transactions_silver_df = (transactions_bronze_df.withColumn("transaction_amount", col("transaction_amount").cast(DecimalType(18,2)))
                              .withColumn("transaction_date", col("transaction_date").cast(TimestampType()))
                             .where((col("payment_status") == "COMPLETED") &
                                     (col("transaction_amount") > 0) &
                                     (col("promo_id").isNotNull()) &
                                     (col("transaction_id").isNotNull())))

    promotions_silver_df = (promotions_bronze_df.withColumn("discount_pct", col("discount_pct").cast(DecimalType(5,2)))
                            .where((col("promo_id").isNotNull()) &
                                   (col("channel").isin("Email", "SMS", "Push")) &
                                   (col("discount_pct").between(0, 100))))

    # Deduplicate and join with merchants
    transactions_silver_df = (transactions_silver_df.dropDuplicates(["transaction_id"])
                                             .orderBy(col("ingestion_timestamp").desc())
                                             .withWatermark("ingestion_timestamp", "1 hour"))

    merchants_df = (spark.read.format("parquet")
                    .load(merchants_path)
                    .hint("broadcast"))

    transactions_silver_df = (transactions_silver_df.join(broadcast(merchants_df), "promo_id", "left")
                              .withColumn("quality_flag", when(col("promo_id").isNotNull(), "CLEAN").otherwise("UNMATCHED")))

    # Write data to Silver layer
    transactions_silver_df.write.partitionBy("transaction_date").parquet(f"{output_path}/transactions")
    promotions_silver_df.write.partitionBy("promo_id").parquet(f"{output_path}/promotions")

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
             .appName("Marketing Attribution Pipeline")
             .getOrCreate())

    # Define paths and run details from .env
    input_path = os.environ["INPUT_PATH"]
    bronze_path = os.environ["BRONZE_PATH"]
    silver_path = os.environ["SILVER_PATH"]
    merchants_path = os.environ["MERCHANTS_PATH"]
    run_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    run_id = f'run_{datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")}'

    # Execute pipeline stages
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    transform_silver(spark, bronze_path, merchants_path, silver_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, min, expr, broadcast, when
from pyspark.sql.types import DecimalType, TimestampType
import json

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    transactions_df = (spark.read.parquet(silver_path)
                       .withColumn("transaction_amount", col("transaction_amount").cast(DecimalType(18,2)))
                       .withColumn("transaction_date", col("transaction_date").cast(TimestampType())))

    # Filter for completed transactions
    completed_transactions_df = transactions_df.filter(col("payment_status") == "COMPLETED")

    # Aggregate metrics for merchants
    merchant_performance_df = (completed_transactions_df.groupBy("merchant_id", "merchant_name", "category", "city", "transaction_date")
                               .agg(sum("transaction_amount").alias("total_revenue"),
                                    count("*").alias("txn_count"),
                                    (count(when(col("payment_status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")))

    # Write output partitioned by date
    merchant_performance_df.write.partitionBy("transaction_date").parquet(output_path)

def build_customer_ltv(spark, silver_path):
    # Read Silver layer transactions data
    transactions_df = (spark.read.parquet(silver_path)
                        .withColumn("transaction_amount", col("transaction_amount").cast(DecimalType(18,2)))
                       .filter(col("payment_status") == "COMPLETED"))

    # Aggregate metrics for customers
    customer_ltv_df = (transactions_df.groupBy("customer_id") 
                       .agg(sum("transaction_amount").alias("total_spent"),
                            count("*").alias("total_txns"), 
                            avg("transaction_amount").alias("avg_txn_value"),
                            min("transaction_date").alias("first_txn_date"),
                            max("transaction_date").alias("last_txn_date"),
                            broadcast(transactions_df.groupBy("customer_id", "payment_method")
                                                     .count())
                                                     .alias("payment_methods")
                                                     .selectExpr("customer_id", 
                                                                  expr("mode(payment_method) within group (order by count) as preferred_payment_method")))

    # Write output as a single cumulative file
    customer_ltv_df.write.parquet(silver_path.replace("silver", "ltv"))

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    transactions_df = (spark.read.parquet(silver_path)
                      .withColumn("transaction_amount", col("transaction_amount").cast(DecimalType(18,2)))
                      .filter(col("payment_status") == "COMPLETED"))

    # Aggregate daily summary metrics
    daily_summary_df = (transactions_df.groupBy("transaction_date")
                       .agg(sum("transaction_amount").alias("total_revenue"),
                             count("*").alias("total_txns"),
                             countDistinct("customer_id").alias("unique_customers"),
                             countDistinct("merchant_id").alias("unique_merchants"),
                             (count(when(col("payment_status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")))

    # Write output partitioned by date
    daily_summary_df.write.partitionBy("transaction_date").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_output = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output = f"{gold_output_dir}/customer_ltv"
    daily_summary_output = f"{gold_output_dir}/daily_summary"

    # Run each gold layer function
    build_merchant_performance(spark, silver_path, merchant_performance_output, run_date)
    build_customer_ltv(spark, silver_path)
    build_daily_summary(spark, silver_path, daily_summary_output, run_date)

    # Create run metadata
    run_metadata = {
        "run_date": run_date,
        "output_paths": {
            "merchant_performance": merchant_performance_output,
            "customer_ltv": customer_ltv_output,
            "daily_summary": daily_summary_output
        }
    }

    # Write run metadata to JSON
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

if __name__ == "__main__":
    spark = (SparkSession.builder
            .appName("Marketing Attribution Pipeline")
             .getOrCreate())

    silver_path = os.environ["SILVER_PATH"]
    gold_output_dir = os.environ["GOLD_OUTPUT_DIR"]
    run_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    run_gold(spark, silver_path, gold_output_dir, run_date)
